name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25.3

    steps:
    - uses: actions/checkout@v3
    - name: Setup greptimedb
      run: |
        GREPTIMEDB_VER=v0.2.0
        DOWNLOAD_URL=https://github.com/GreptimeTeam/greptimedb
        curl -L ${DOWNLOAD_URL}/releases/download/${GREPTIMEDB_VER}/greptime-linux-amd64.tgz -o /tmp/greptimedb-${GREPTIMEDB_VER}-linux-amd64.tar.gz
        mkdir -p /tmp/greptimedb-download
        tar xzvf /tmp/greptimedb-${GREPTIMEDB_VER}-linux-amd64.tar.gz -C /tmp/greptimedb-download
        rm -f /tmp/greptimedb-${GREPTIMEDB_VER}-linux-amd64.tar.gz
        nohup /tmp/greptimedb-download/greptime standalone start > /tmp/greptimedb.log 2>&1 &
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: |
        cat /tmp/greptimedb.log
        rebar3 ct --cover
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Covertool
      run: rebar3 covertool generate
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true
        env_vars: 25.3
